### ISSUE TITLE
No compatibility with BYG flowers.

### ISSUE THREAD

**Issue by crabdancing** [Trikzon/flourish#2]
BYG adds a collection of nice flowers that it'd be nice to multiply. :)

**Comment by Trikzon** [comment]
I can definitely look into it!

If you want it done faster, there is a config file that is easy to add blocks to. If you do that and send the file here I can add it to the mod soon after. Otherwise, I'll do it myself within the week.

**Comment by crabdancing** [comment]
Oh cool. I'll try to do that if I can get to it. :)

Isn't there a tag convention for flowers that could be used to make this kind of thing easier? Maybe I could ask the BYG people to add a flower tag to their flowers so that way you just need to add one tag to your mod.

**Comment by crabdancing** [comment]
It would make sense to have two tags -- one for tall flowers and one for short flowers, and to try to standardize them to make mods work together more dynamically.

**Comment by Trikzon** [comment]
There *might* be a vanilla tag for flowers, but we wouldn't be able to use that because then it would include vanilla tall flowers which already have this feature.
Also, I'm still not completely sold on tags compared to a config file as a config file, imo, is much easier for a user to edit than them having to 1. make a datapack 2. copy it to each world and 3. research what tags mods add.

Technically there is a tag that this mod adds that any mod could use and it will work. So if you want to go in that direction, that sounds good to me.

I don't really see the purpose of two different tags for tall and regular flowers

**Comment by crabdancing** [comment]
IDK, it might be useful to distinguish between tall and regular in tags. For instance, if you have a mod that adds a macerator that more efficiently grinds up resources, its recipes might want to change dynamically for tall and regular flowers. Tall should give more resources, and whatnot.

**Comment by crabdancing** [comment]
You're right -- config files are way better than data packs IMO. :)

**Comment by crabdancing** [comment]
I think datapacks are most useful for things that that the mod maker didn't _expect_ people to want to customize. It's simple to just use a data driven approach internally and allow people to override with datapacks implicitly through that. But if they're already using json loaders they might as well load them from a config file, honestly :P

It would be a nicer approach if we had a really standardized mod for loading datapacks from config directory or somesuch.

**Comment by crabdancing** [comment]
I asked BYG folks. They already have flower tags, which you can see [here](https://github.com/CorgiTaco/BYG/tree/Fabric-1.16.X/src/main/resources/data/minecraft/tags/blocks).

**Comment by crabdancing** [comment]
Incidentally, apparently this tag is in vanilla too. You might be able to shorten your list considerably.

**Comment by Trikzon** [comment]
Oh, awesome! Didn't know there was a small flowers tag tbh. Probably should have looked that up.

I see you forked the repo, do you plan on making the change to that tag or should I do it?

**Comment by crabdancing** [comment]
I was going to take a crack at it. What do you think we should do? I think since you already added a config file it might be nice to add separate options for vanilla tags, and then set those to true by default, and then keep the tag you already added as an option for player customization. Turn it into a whitelist thing.

**Comment by Trikzon** [comment]
Maybe it would make sense to change the config file entirely.

So the new one I propose is:

```json
{
    "flowers": [
    ],
    "small_flowers_tag": true,
    "wither_rose": true,
    "dispenser": true
}
```

That way mods that use the small_flowers tag will be included by default and other things can be added.
Sadly, if a player wants to remove flowers they would have to take out the tag and list every flower... but I think that would be rare enough to not be a problem (and there's probably a craft-tweaker like mod that lets you edit tags somewhere).
Because of this, there would be a wither_rose override because I can see people might want to disable that one.

A problem could be compatibility with the old config. I need to remember to start putting config version #'s in the config file...

**Comment by crabdancing** [comment]
Ah... good idea. I didn't include the wither rose thing in my PR, but it's probably best to separate out changes in conceptual stages via commit history anyway.

**Comment by crabdancing** [comment]
Oh wait... does Minecraft already do the logic to tall flowers via the tag? That _would_ make sense. :S

Whoops. Sorry, I just woke up.

**Comment by Trikzon** [comment]
No problem :)

btw, if you'd like I can bring this to the other versions tomorrow instead of you having to do that

**Comment by crabdancing** [comment]
I just took a peek at Minecraft's source, and it just checks 'fertilizable' and then calls an 'on fertilize' function, which in the vanilla tall flowers drops items. If we want to handle mods that don't have their flowers set up properly, maybe we should check if they're NOT fertilizable and then dupe those, for tall flowers?

**Comment by Trikzon** [comment]
:+1:

**Comment by crabdancing** [comment]
Yeah, I have to go to a lunch date today with a friend. :) I'm glad I could help improve this mod, tho! :D

**Comment by crabdancing** [comment]
Ah it works as is. I'm surprised. Tested on rose bushes, sunflowers, and a few BYG flowers... only produces one for each.
